### ISSUE TITLE
What happens when .set fails?

### ISSUE THREAD

**Issue by petemill** [bevacqua/local-storage#4]
In the README, it's specified that, upon .set, the function will return whether the operation fails. However, it does not state what kind of object will be returned, i.e. a string, booleon or actual Error object.

I guess this is an issue with the documentation and if this can't be updated easily, then I'll go in to the source code and find out. If I do, I'll do a pull request for the docs.

Thanks for the great library!

**Comment by bevacqua** [comment]
It returns whether the operation succeeds, e.g: `true` if successful, `false` otherwise. [Relevant source code](https://github.com/bevacqua/local-storage/blob/master/local-storage.js#L18-L25).

``` js

function set (key, value) {
  try {
    ls.setItem(key, JSON.stringify(value));
    return true;
  } catch (e) {
    return false;
  }
}
```

DOM errors are suppressed. The most common failure (the only one I actually had happen) is where the storage quota is exceeded. This exception also happens in unexpected situations like doing `localStorage.setItem` in incognito-mode-Safari.

**Comment by petemill** [comment]
Great, thanks
